### ISSUE TITLE
Ability to update data or URL for a given hash

### ISSUE THREAD

**Issue by t27** [edwardhotchkiss/short#36]
I would really love to have a feature to update the data or URL corresponding to a given hash. the reason being that I don't want to fiddle with the mongo database used by mongoose directly.

I intend to implement it for myself, and would definitely love to push it upstream as well, 

The api could be 
```
short.update(hash,{
  URL: '',
  data: ''
}
```
of course, the `URL` and `data` are optional(one might not want to update both), and the new keys in `data` will add to the existing keys if not present, and update the existing key if the key is already present.

Let me know what you think and if you have any api preferences for this feature

**Comment by edwardhotchkiss** [comment]
Feel free to do a PR, thanks :)

**Comment by t27** [comment]
Merged PR hence closing the issue. Thanks :+1: :smile:
